<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <RootNamespace>dotnet_http</RootNamespace>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dotnet-http</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.4.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>dotnet-http</PackageId>
    <PackageVersion>$(Version)</PackageVersion>
    <Title>dotnet-http</Title>
    <Authors>Christophe Nasarre</Authors>
    <Owners>chrisnas</Owners>
    <Description>Global CLI tool to detail HTTP requests</Description>
    <Copyright>Copyright Christophe Nasarre $([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/chrisnas/ClrEvents</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/chrisnas/ClrEvents</RepositoryUrl>
    <PackageTags>HTTP HttpClient TraceEvent Perfview</PackageTags>
    <PackageReleaseNotes>Upgrade references version and support newer .NET versions.</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
    <None Include="LICENSE" Pack="true" PackagePath="\"/>
  </ItemGroup>

    <ItemGroup>
    <ProjectReference Include="..\Events.Shared\Events.Shared.csproj" />
  </ItemGroup>

</Project>
