<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>dotnet_wait</RootNamespace>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dotnet-wait</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>dotnet-wait</PackageId>
    <PackageVersion>$(Version)</PackageVersion>
    <Title>dotnet-wait</Title>
    <Authors>Christophe Nasarre</Authors>
    <Owners>chrisnas</Owners>
    <Description>Global CLI tool to list waits duration</Description>
    <Copyright>Copyright Christophe Nasarre $([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/chrisnas/ClrEvents</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/chrisnas/ClrEvents</RepositoryUrl>
    <PackageTags>Wait Lock Contention TraceEvent Perfview</PackageTags>
    <PackageReleaseNotes>Upgrade references version and support newer .NET versions</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IgnoresAccessChecksToGenerator" Version="0.8.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Diagnostics.NETCore.Client" Version="0.2.661903" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsAssemblyName Include="Microsoft.Diagnostics.NETCore.Client" />
    <InternalsAssemblyName Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Events.Shared\Events.Shared.csproj" />
  </ItemGroup>

</Project>
